# Clipman support (requires clipman and wl-paste)

# Setup clipman
exec wl-paste -t text --watch clipman store

# Setup clipboard selector
bindsym $mod+v exec "clipman pick -t rofi -T'-config ~/.config/sway/rofi-config/config.rasi' --err-on-no-selection && wtype -M ctrl -M shift v"