# Clipman support (requires cliphist and wl-paste)

# Setup clipman
exec wl-paste -t text --watch cliphist store

# Setup clipboard selector
bindsym $mod+v exec "rofi -modi clipboard:cliphist-rofi-img -show clipboard -show-icons -config ~/.config/sway/rofi-config/config.rasi"
