# Use app id "dropdown" to identify this kitty window separately from others
# --class and --app-id do the same thing
# If the terminal crashes or is closed, we can get it back with "kitty --app-id dropdown" in run menu
set $app-id dropdown
set $term kitty --app-id dropdown

# Set window rules for the dropdown terminal
# floating makes it float instead of tile, border pixel removes the title bar, sticky enable makes it persist between workspaces
# Then resize it to fit the monitor and move it to the scratchpad
# NOTE: match by class for X11 (i3), by app_id for Wayland (Sway)
for_window [app_id="$app-id"] floating enable, border pixel, sticky enable
for_window [app_id="$app-id"] move container to scratchpad

# Execute the terminal
exec $term

# Toggle terminal visibility with mod+Tab
# Use "move position 0 0" to have it appear within the workspace instead of in the absolute top corner
# We resize here to avoid issues resizing terminals which try to resize themselves on startup
bindsym $mod+Tab [app_id="$app-id"] scratchpad show, resize set width 100ppt height 50ppt, move position 0 0
