# Startup obs studio (flatpak)
exec --no-startup-id flatpak run com.obsproject.Studio --minimize-to-tray

# Start replay buffer
exec obs-cmd replay start

# Hotkey to capture clip (mod shift r)
# Play a sound before saving the clip to make it clear it worked
bindsym $mod+Shift+r exec obs-cmd replay save && paplay /usr/share/sounds/freedesktop/stereo/bell.oga