# Startup obs studio (flatpak)
exec --no-startup-id flatpak run com.obsproject.Studio --minimize-to-tray

# Start replay buffer
exec obs-cmd replay start

# Hotkey to capture clip (alt shift s, may change later)
bindsym Mod1+Shift+s exec obs-cmd replay save