# Swaywsr - run once at startup then whenever reloading kill and rerun
exec ~/dev/swaywsr/target/release/swaywsr
#exec_always pgrep -x swaywsr > /dev/null && pkill -x swaywsr; ~/dev/swaywsr/target/release/swaywsr

# Run startup applications
exec --no-startup-id flatpak run io.gitlab.librewolf-community
exec --no-startup-id steam
exec --no-startup-id flatpak run dev.vencord.Vesktop
exec --no-startup-id flatpak run org.mozilla.Thunderbird

# Tray apps
exec --no-startup-id flatpak run pw.mmk.OpenFreebuds

# Special key to take a screenshot with Slurp + Grim + Still
bindsym $mod+Shift+s exec ~/dev/still/build/still -c 'grim -g "$(slurp)" -t png - | wl-copy -t image/png'
