# Swaywsr - run once at startup then whenever reloading kill and rerun
exec ~/dev/swaywsr/target/release/swaywsr
#exec_always pgrep -x swaywsr > /dev/null && pkill -x swaywsr; ~/dev/swaywsr/target/release/swaywsr

# Run startup applications
exec --no-startup-id flatpak run io.gitlab.librewolf-community
exec --no-startup-id steam
exec --no-startup-id flatpak run dev.vencord.Vesktop

# Force Steam into workspace 2, Vesktop to workspace 6 and Evolution to workspace 7
for_window [app_id="librewolf"] move to workspace number 1
for_window [class="steam"] move to workspace number 2
for_window [app_id="vesktop"] move to workspace number 6
for_window [app_id="org.gnome.Evolution"] move to workspace number 7

# Special key to take a screenshot with Grim
bindsym $mod+Shift+s exec grim -g "$(slurp)" -t png - | wl-copy -t image/png
