# swaywsr
exec swaywsr --config "${XDG_CONFIG_HOME:-$HOME/.config}/sway/swaywsr-config/config.toml"

# autotiling-rs
exec autotiling-rs

# Run startup applications
exec --no-startup-id flatpak run io.gitlab.librewolf-community
exec --no-startup-id flatpak run dev.vencord.Vesktop
exec --no-startup-id flatpak run org.mozilla.Thunderbird

# Tray apps
exec --no-startup-id flatpak run pw.mmk.OpenFreebudse
exec --no-startup-id flatpak run io.github.tobagin.karere

# Special key to take a screenshot with Slurp + Grim + Still
bindsym $mod+Shift+s exec still -c 'grim -g "$(slurp)" -t png - | wl-copy -t image/png'
