# Force Steam into workspace 2, Vesktop to workspace 6 and Evolution to workspace 7
for_window [app_id="librewolf"] move to workspace number 1
for_window [class="steam"] move to workspace number 2
for_window [app_id="vesktop"] move to workspace number 6
for_window [app_id="org.mozilla.Thunderbird"] move to workspace number 7
for_window [app_id="com.obsproject.Studio"] move to workspace number 8

# Window transparency presets
set $low_opacity 0.95
set $medium_opacity 0.9
set $high_opacity 0.8

# Games on workspace 5, inhibit idle when focused
for_window [app_id="gamescope"] move to workspace number 5, inhibit_idle visible # Anything using gamescope
for_window [app_id="steam_app_*"] move to workspace number 5, inhibit_idle visible # Any other steam game (wayland)
for_window [class="steam_app_*"] move to workspace number 5, inhibit_idle visible # Any other steam game (x11/xwayland)
for_window [app_id="Minecraft*"] move to workspace number 5, inhibit_idle visible # Minecraft
for_window [app_id="HytaleClient"] move to workspace number 5, inhibit_idle visible # Hytale game

# Display [XWayland] for apps using XWayland
for_window [shell="xwayland"] title_format "[XWayland] %title"

# Bluetooth manager floats
for_window [app_id="blueman-manager"] floating enable, move position center

# Float extension popups for browser
for_window [title="Extension"] floating enable, move position center

# Set opacity preferences for individual apps
for_window [app_id="kitty"] opacity $medium_opacity
for_window [app_id="dropdown"] opacity $medium_opacity
for_window [app_id="mousepad"] opacity $low_opacity
for_window [app_id="CoolerControl"] opacity $medium_opacity