# Window transparency presets
set $low_opacity 0.95
set $medium_opacity 0.9
set $high_opacity 0.8

# Gamescope on workspace 5
for_window [app_id="gamescope"] move to workspace number 5

# Display [XWayland] for apps using XWayland
for_window [shell="xwayland"] title_format "[XWayland] %title"

# Bluetooth manager floats
for_window [app_id="blueman-manager"] floating enable, move position center

# Float extension popups for browser
for_window [title="Extension"] floating enable, move position center

# Set opacity preferences for individual apps
for_window [app_id="kitty"] opacity $medium_opacity
for_window [app_id="dropdown"] opacity $medium_opacity
for_window [app_id="mousepad"] opacity $low_opacity
for_window [class="steam"] opacity $low_opacity
for_window [app_id="CoolerControl"] opacity $medium_opacity

for_window [floating] opacity $medium_opacity